### ISSUE TITLE
Remove or embed JQuery dependency

### ISSUE THREAD

**Issue by Antoine-dh** [grongierisc/JsonTraceViewer#6]
In a restricted network environment, rendering might fail if [jquery](https://code.jquery.com/jquery-2.1.1.min.js) cannot be accessed
Can you consider removing this dependency or embed it as a local file in the module?

https://github.com/grongierisc/JsonTraceViewer/blob/2d038af3b935a79bcf25b55105a6a5a0c0bf1123/src/cls/Grongier/JsonTraceViewer/Message.cls#L20C24-L20C67

**Comment by grongierisc** [comment]
good idea, but i'm concern by cache an performance.

version 1.1.0 include the embedded jquery
